### ISSUE TITLE
Readme:  Broken Link to Blog

### ISSUE THREAD

**Issue by oscarluke** [nshki/chusaku#16]
There is a borked link in the development section of the readme. - https://nshki.com/chusaku-a-controller-annotation-gem/ 

I think GitHub is not happy with the last "/" at the end of the URL.

`https://nshki.com/chusaku-a-controller-annotation-gem/` does not work
`https://nshki.com/chusaku-a-controller-annotation-gem` works

https://github.com/nshki/chusaku/blob/master/README.md#development

**Comment by nshki** [comment]
Thanks, good sir. Just fixed up the config on the blog side of things. Both links now work.
