### ISSUE TITLE
Missing route name on aliased CRUD actions

### ISSUE THREAD

**Issue by vlad-pisanov** [nshki/chusaku#34]
Consider this routing (`update` is aliased as `change`):
```ruby
resources :invitations do
  collection do
    put :update, as: :change
  end
end
```

Chusaku annotates the `update` action like so (`change_invitation` is present, but the standard `invitation` is missing):
```ruby
# @route PUT /invitations (change_invitations)
# @route PATCH /invitations/:id
# @route PUT /invitations/:id
def update; end
```

Strangely, if I change it to `resources :invitations, only: [:update]`, everything works as expected: 🤔 
```ruby
# @route PUT /invitations (change_invitations)
# @route PATCH /invitations/:id (invitation)
# @route PUT /invitations/:id (invitation)
def update; end
```

**Comment by nshki** [comment]
Thanks for reporting this, @vlad-pisanov! I was able to reproduce what you described, and it does indeed seem to be a bug. I'll spend more time on this and will keep this thread updated.

**Comment by nshki** [comment]
@vlad-pisanov would you mind giving this potential fix a try?

1. Change your Gemfile so you're temporarily pointing to the fix branch:

    ```ruby
      gem "chusaku", git: "https://github.com/nshki/chusaku.git", branch: "fix/missing-route-names", require: false
    ```
2.

**Comment by vlad-pisanov** [comment]
@nshki it works! 🙌 No regressions either (tested on a very large codebase with thousands of routes)

**Comment by nshki** [comment]
Fantastic! Thanks for verifying. 😄 Will be releasing a patch shortly!
