### ISSUE TITLE
Include a rake task for invoking chusaku

### ISSUE THREAD

**Issue by G-Rath** [nshki/chusaku#40]
It would be nice if we had a rake task that could be used to invoke `chusaku` so that it could be easily integrated with rake-based workflows i.e. our codebases use both `chusaku` and `annotate_models`, so I'd like to create a general `dev:annotate` task that invokes both.

Technically I should be able to call `chusaku` programmatically but that would require understanding more of the internal classes than I'd like (and in every application!), and overall this feels like something reasonable for the gem to carry.

For reference, this is the rake tasks provided by `annotate_models`: https://github.com/ctran/annotate_models/blob/develop/lib/tasks/annotate_models.rake

**Comment by nshki** [comment]
Thanks for the suggestion! I agree, this would be a nice addition for Rake-based workflows and seems reasonable for the gem to ship with out of the box. I'll see if I can put some time towards this in the coming days.

**Comment by nshki** [comment]
I noticed in Annotate's gem they use environment variables to pass arguments to their Rake task. Is that a pattern that's preferred for Rake-based workflows?

e.g.

```sh
DRY_RUN=1 VERBOSE=1 bin/rake chusaku
```

I suppose that's a bit easier than having to do something like:

```sh
bin/rake chusaku[true, true, "some string"]
```

**Comment by nshki** [comment]
@G-Rath would you mind taking a look at #41 for me to see if this satisfies what you're looking for?
