### ISSUE TITLE
Exclude `vendor` directory by default

### ISSUE THREAD

**Issue by G-Rath** [nshki/chusaku#53]
With the release of #48 our CI is now failing because by default `ruby/setup-ruby` vendors gems, so the `DEFAULT_CONTROLLERS_PATTERN` of `**/*_controller.rb` now picks up controllers in gems such as `good_job`, `devise`, and `active_storage`.

This does mean that v1.3.0 is technically breaking, though I think rather than revert or do a new major a sensible fix would be to just the `vendor` directory - you should be able to do this with an almost equivalent glob like `{[!vendor/]**/*,*}/*_controller.rb` (I think the only downside with that is you'll match `vendor/*_controller.rb`, but I don't know why you'd ever have a `*_controller.rb` directly in `vendor` itself?), or explicitly filter it out with a flag like `--include-vendor` (which could be added later if/when requested)

**Comment by nshki** [comment]
Thanks for reporting and diagnosing, @G-Rath! I think a glob that rules out `vendor/` by default seems reasonable. If for some reason a project _does_ want to annotate controllers in `vendor/`, they'll be able to define their own custom glob using `-c/--controllers-pattern`.

**Comment by nshki** [comment]
@G-Rath I opened #54 as a proposed solution to this issue. I was able to test on my own projects, but I'd really appreciate it if you could take a look to see if that solves your CI problem. If not, not a problem!

**Comment by G-Rath** [comment]
@nshki that works great, thanks!
