### ISSUE TITLE
Unable to properly annotate parent methods used by child controllers

### ISSUE THREAD

**Issue by G-Rath** [nshki/chusaku#57]
With the following:

```
# app/controllers/inner/base_controller.rb
class Inner::BaseController < ApplicationController
  # @route GET /inner/videos (inner_videos)
  def show
    #
  end
end

# app/controllers/inner/images_controller.rb
class Inner::ImagesController < Inner::BaseController

end

# app/controllers/inner/videos_controller.rb
class Inner::VideosController < Inner::BaseController

end

# config/routes.rb
Rails.application.routes.draw do
  namespace :inner do
    resource :images, only: [] do
      get :show, on: :member
    end

    resource :videos, only: [] do
      get :show, on: :member
    end
  end
end
```

We get an inf. annotation cycle:
```
❯ bundle exec chusaku --verbose --exit-with-error-on-annotation
Annotated -/app/controllers/inner/base_controller.rb
Annotated -/app/controllers/inner/base_controller.rb
Chusaku has finished running.
Exited with status code 1.

❯ bundle exec chusaku --verbose --exit-with-error-on-annotation
Annotated -/app/controllers/inner/base_controller.rb
Annotated -/app/controllers/inner/base_controller.rb
Chusaku has finished running.
Exited with status code 1.
```

My guess is that it's probably the result of something attempting to avoid duplication which doesn't have enough info in its key, so it ends up with just the last route

**Comment by G-Rath** [comment]
fwiw it doesn't seem like pattern is picked up by `chusaku` at all pre v1.3, which is probably why it wasn't discovered until now

**Comment by nshki** [comment]
Thanks so much for reporting! Just acknowledging that I saw this and I'll be digging into this when time allows. 🙇🏻

**Comment by nshki** [comment]
This is an interesting case that I haven't considered before. Is the expectation here that the annotations should live in the parent controller? I could see a world where I'd want to see annotations in the child controllers too, maybe?

**Comment by G-Rath** [comment]
I feel like ideally you'd have annotations in the child controller to make it more obvious that the controller is inheriting (potentially a lot) of routes - but then I think the challenge is you could end up with a large wall of comments (my example isn't actually far off from what we've got in our actual app: our base controller has 5 endpoints, and our child controllers mostly have just `private` methods).

Personally I think it could be nice to see something like this:

```
class Inner::ImagesController < Inner::BaseController
  # @route GET /inner/videos (inner_videos)
  # def index; end

  # @route GET /inner/video/:id (inner_video)
  # def show; end
end
```

But then that would be more complex both in terms of implementation and what the output is, and some folks might have a different style...

It's a tricky one, though I don't think it necessarily needs to be solved all at once either - right now our blocker is the bug that it always thinks there's something to annotate, which is different from how the annotations get styled so I think it could be fine to start just adding all of the annotations to the parent controller, then revisit if it would make sense to try annotating the child controllers

**Comment by nshki** [comment]
Yeah, I agree with you. I'll focus on fixing the bug at hand and then will give the other idea a longer think.

**Comment by nshki** [comment]
@G-Rath would you mind giving this solution a try and let me know how it works for you? I was able to reproduce the issue and fix locally and via tests, but want to make sure things work as expected for you too.

```ruby
gem "chusaku", require: false, git: "https://github.com/nshki/chusaku.git", branch: "fix/inherited-actions"
```

**Comment by G-Rath** [comment]
@nshki this looks to be working for me!
